type%foo t += T [@@foo]
 class%foo x = x [@@foo]
 class type%foo x = x [@@foo]
 external%foo x : _ = "" [@@foo]
 exception%foo X [@foo]
 module%foo M = M [@@foo]
 module%foo rec M : S = M [@@foo]
 and M : S = M [@@foo]
 module type%foo S = S [@@foo]
 include%foo M [@@foo]
 open%foo M [@@foo]