(lang dune 2.8)
(name menhir)
(using menhir 2.0)
(version 20231231)

(package
  (name menhirLib)
)

(package
  (name menhirCST)
)

(package
  (name menhirSdk)
)

(package
  (name menhir)
)

(package
  (name coq-menhirlib)
)
